// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vemsneacoaixmeiboyqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlbXNuZWFjb2FpeG1laWJveXF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjgxOTcsImV4cCI6MjA2OTU0NDE5N30._Zaw8OThYhhd9zefN9OvbxM0QFBndkvAWT0nM7PpdsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});